version: '3.8'
services:
  app:
    container_name: app
    build: ./
    environment:
      - SERVER=db
      - DATABASE=task_manager
      - USER=task_manager
      - PASSWORD=password
    volumes:
      - ./:/var/www/html/
      - ./apache.conf:/etc/apache2/sites-enabled/default.conf
      - ./nice-worker.conf:/etc/supervisor/conf.d/nice-worker.conf
    ports:
      - 8000:80

  db:
    container_name: db
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_manager
      MYSQL_USER: task_manager
      MYSQL_PASSWORD: password
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db